# Generated by Django 5.2.4 on 2025-08-08 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='fruites/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('f1', 'mango'), ('f2', 'apple'), ('f3', 'kiwi'), ('f5', 'banana'), ('f6', 'date')], max_length=2)),
            ],
        ),
    ]
