# Generated by Django 5.2.4 on 2025-08-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruittype',
            name='descriptionb',
            field=models.TextField(default=''),
        ),
    ]
